include:
  - mdns.yaml
services:
  diyws:
    image: diyws
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
